name:
  Scrap test

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check updates
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: setup libs
        run: |
          pip install --upgrade pip |
          pip install -r requirements.txt

      - name: Linting
        run: flake8
